#lang racket

(require eopl)

(provide lang-name lang-scan lang-parse lang-eval-expr)

; The language name
(define lang-name "LET")

; Primitive functions and their evaluators
(define primitives (list
  (cons "zero?" zero?)
  (cons "minus" (lambda (x) (- 0 x)))

  (cons "+" +)
  (cons "-" -)
  (cons "*" *)
  (cons "/" /)
  (cons "equal?"   equal?)
  (cons "greater?" >)
  (cons "less?"    <)
))

; Lexical specification
(define lexer-spec '(
  ; Skip all whitespace
  (white (whitespace) skip)

  ; Integers
  (number (digit (arbno digit)) number)

  ; Identifiers
  (identifier ((or letter "+" "-" "*" "/") (arbno (or letter digit "?"))) string)
))

; Grammar specification
(define grammar-spec '(
  ; Primitive number expression
  (expression (number) expr-number)

  ; Expression beginning with an identifier
  (expression (identifier ident-tail) expr-ident-start)

  ; Let expression
  (expression ("let" identifier "=" expression "in" expression) expr-let)

  ; Conditional
  (expression ("if" expression "then" expression "else" expression) expr-if)

  ; Tail of identifier expressions (primitive and compound expressions)
  (ident-tail () ident-tail-empty)
  (ident-tail ("(" (separated-list expression ",") ")") ident-tail-compound)
))

; Define datatypes from the grammar
(sllgen:make-define-datatypes lexer-spec grammar-spec)

; Create parsers
(define lang-scan  (sllgen:make-string-scanner lexer-spec grammar-spec))
(define lang-parse (sllgen:make-string-parser  lexer-spec grammar-spec))

; Evaluate compound expression
(define (eval-compound type exprs)
  ; Get operator
  (let ((oper-pair (assoc type primitives)))
    (if oper-pair
      ; Accepting the correct number of args?
      (if (procedure-arity-includes? (cdr oper-pair) (length exprs))
        ; OK, execute function over evaluated expressions
        (apply (cdr oper-pair) (map lang-eval-expr exprs))

        ; Bad argument count
        (eopl:error 'lang-arg-count "Wrong number of arguments for operator ~s" type)
      )

      ; Bad operator
      (eopl:error 'lang-undefined "Undefined operator ~s" type)
    )
  )
)

; Evaulates an expression tree generated by (lang-parse)
(define (lang-eval-expr tree)
  (cases expression tree
    ; Numeric expression
    (expr-number (num) num)

    ; Ident start expression
    (expr-ident-start (ident tail)
      (cases ident-tail tail
        ; Primitive identifier
        (ident-tail-empty () (error 'unimplemented))

        ; Compound expression
        (ident-tail-compound (exprs) (eval-compound ident exprs))
      )
    )

    ; Let expression
    (expr-let (name value expr) (error 'unimplemented))

    ; Conditional
    (expr-if (expr true false)
             (if (lang-eval-expr expr) (lang-eval-expr true) (lang-eval-expr false)))
))
